version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

#workflows:
#  heroku_deploy:
#    jobs:
#      - build
#      - heroku/deploy-via-git:
#          requires:
#            - build
#          filters:
#            branches:
#              only: sequential-branch-filter

jobs:
  build:

    working_directory: ~/tosh

    docker:
      - image: circleci/openjdk:11.0-jdk-stretch

    steps:
      - checkout
      - heroku/install
      - restore_cache:
          key: tosh-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      #      - heroku/deploy-via-git

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package
      - setup_remote_docker
      - run: docker build -f src/main/docker/Dockerfile.jvm -t quarkus/tosh .
      - run: docker tag quarkus/tosh registry.heroku.com/shrouded-woodland-80423/web
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker push registry.heroku.com/shrouded-woodland-80423/web
      - run: heroku container:release web -a shrouded-woodland-80423

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/wikiquiz-1.0.0-SNAPSHOT-runner.jar