version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/tosh

    docker:
      - image: circleci/openjdk:11.0-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: tosh-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/wikiquiz-1.0.0-SNAPSHOT-runner.jar